version: '3.8'

networks:
  rag_network:
    driver: bridge

services:
  db:
    networks:
      - rag_network
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rag
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/app/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    networks:
      - rag_network
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"  # Management UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    networks:
      - rag_network
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      ROLE: api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: rag
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      UPLOAD_DIR: /data/uploads
      DATA_DIR: /data
      SENTENCE_TRANSFORMERS_HOME: /models
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - app_data:/data  # All data outside app folder
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: /start.sh

  worker:
    networks:
      - rag_network
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      ROLE: worker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: rag
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      UPLOAD_DIR: /data/uploads
      DATA_DIR: /data
      SENTENCE_TRANSFORMERS_HOME: /models
    volumes:
      - ./backend:/app
      - app_data:/data  # Shared with API
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    command: /start.sh

  frontend:
    networks:
      - rag_network
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      API_BASE: http://api:8000
    ports:
      - "8501:8501"
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  app_data:  # Single volume for all app data (uploads, models, etc.)